### ISSUE TITLE
Are code blocks rendering correctly?

### ISSUE THREAD

**Issue by joshbochu** [vercel/nextjs-portfolio-starter#10]
Curious if the code blocks on the demo app are rendering with the proper syntax highlighting. I've attached a snippet from [here](https://demo.vercel.blog/posts/pages)

![image](https://user-images.githubusercontent.com/70353384/155830164-3d9d5d26-40b6-4985-bc72-ec0d75d31b58.png)

Based on the documentation from [Nextra](https://nextra.vercel.app/features/mdx), I'd expect it to have some color. But perhaps I'm missing something!

**Comment by reillyjodonnell** [comment]
You need to add the language that the code snippet is in.

i.e if a typescript snippet you'd use

'''typescript
<code here>
'''
