### ISSUE TITLE
How do i add reactions, comments, paging, search into this starter?

### ISSUE THREAD

**Issue by truongnhatbui** [vercel/nextjs-portfolio-starter#4]
Hi, How do i add reactions, comments, paging, search into this starter?

post reactions
comments from disqus.com
paging posts
search posts and pages

Thank you,
Truong

**Comment by leerob** [comment]
Hey! This starter doesn't cover adding this, but you could absolutely write custom code to achieve those on top of this starter.

We're planning to keep this fairly simple and focused, but if you do end up creating something with reactions or comments on top of this, do let us know 😄

**Comment by truongnhatbui** [comment]
Thanks @leerob
