### ISSUE TITLE
failed to process not yet implemented: proper error reporting for wrong `@jsxRuntime`

### ISSUE THREAD

**Issue by mayank1513** [vercel/nextjs-portfolio-starter#7]
I am getting this error while trying to build this app

```
failed to process not yet implemented: proper error reporting for wrong `@jsxRuntime`
```

**Comment by mayank1513** [comment]
This error comes with next@12 not with next@11.x

Please update repo

**Comment by mayank1513** [comment]
Node version 16

**Comment by leerob** [comment]
Should be fixed with the latest deps upgrade, please let me know if not!
